apiVersion: v1
kind: Service
metadata:
  name: {{ include "wekan.fullname" . }}
  labels:
    {{- include "wekan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{ if .Values.service.externalIPs }}
  externalIPs:
    - {{ .Values.service.externalIPs }}
{{ end }}
  selector:
    {{- include "wekan.selectorLabels" . | nindent 4 }}
